# Generated by Django 5.1.4 on 2025-07-16 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artwork_Posting',
            new_name='ArtworkPosting',
        ),
    ]
