# Generated by Django 5.1.4 on 2025-07-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_rename_artwork_posting_artworkposting'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('photography', 'Photography'), ('pottery', 'Pottery'), ('other', 'Other')], default='pottery', max_length=50)),
                ('location', models.CharField(blank=True, default='', help_text='Enter a geographical address (e.g., 123 Main St, City, Country)', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Enter a detailed description here.', null=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Hourly Rate in USD', max_digits=10)),
            ],
        ),
    ]
