# Generated by Django 5.1.4 on 2025-07-24 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_rentallisting_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artworkposting',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='ArtworkPosting',
        ),
    ]
