# Generated by Django 5.1.4 on 2025-07-25 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rent.rentallisting'),
            preserve_default=False,
        ),
    ]
